### ISSUE TITLE
MOCKQ8DBMS.py

### ISSUE THREAD

**Issue by UCHIHA-MADRA** [rishabh11336/DBMS-OPPE-Prepration#1]
INCORRECT CODE
9788131773383
============================
Creating new PostgreSQL cluster 10/regress ...
/usr/lib/postgresql/10/bin/initdb -D /pg_virtualenv.PvTQhY/data/10/regress --auth-local peer --auth-host md5 --username=nsjail --pwfile=/pg_virtualenv.PvTQhY/postgresql-common/pwfile --nosync
The files belonging to this database system will be owned by user "nsjail".
This user must also own the server process.

The database cluster will be initialized with locale "C.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /pg_virtualenv.PvTQhY/data/10/regress ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default timezone ... Etc/UTC
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok

Sync to disk skipped.
The data directory might become corrupt if the operating system crashes.

Success. You can now start the database server using:

    /usr/lib/postgresql/10/bin/pg_ctl -D /pg_virtualenv.PvTQhY/data/10/regress -l logfile start

Warning: The parent /var/run/postgresql of the selected
stats_temp_directory does not exist. Not adding this setting in
postgresql.conf.
Ver Cluster Port Status Owner  Data directory                        Log file
10  regress 5432 online nsjail /pg_virtualenv.PvTQhY/data/10/regress /pg_virtualenv.PvTQhY/log/postgresql-10-regress.log

DROP DATABASE
CREATE DATABASE
CREATE ROLE
END_OF_INSIDE_VIRTUALENV
Dropping cluster 10/regress ...

![image](https://user-images.githubusercontent.com/68822532/230352436-af4a1367-149f-42eb-a4d5-3bc6b37e3f04.png)

**Comment by rishabh11336** [comment]
![image](https://user-images.githubusercontent.com/67859818/230677868-5a1095d8-171a-4cdf-a852-1239b19ada8b.png)

Check the function you have in your question.
L2(x) = 2000 + 4*x
It must be different
